apache/rocketmq-client-cpp

include/CCommon.h, include/CMessage.h, include/CMessageExt.h, include/CProducer.h, include/CPullConsumer.h, include/CPullResult.h, include/CPushConsumer.h, src/extern/CMessage.cpp, src/extern/CMessageExt.cpp, src/extern/CProducer.cpp, src/extern/CPullConsumer.cpp, src/extern/CPushConsumer.cpp
In order to connect RocketMQ, a c-style client is needed.
Add C style APIs.
Support Session Credentials
Enhance C APIs
- [] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean …
=> [FEATURE REQUEST #488]Export C-style APIs for RocketMQ client

include/CProducer.h, src/extern/CProducer.cpp
What is the purpose of the change
Add add C-API SendMessageOneway.
Brief changelog
The definition of SendMessageOneway interface is added to the CProducer.h  .
The SendMessageOneway interface is implemented in the  CProducer.cpp.
=> add C-API SendMessageOneway

README.md, build.sh, src/producer/StringIdMaker.cpp, src/producer/StringIdMaker.h
1、update boost version from 1.56 to 1.58
2、add exist script when build error of build.sh
3、resolve a bug for build.sh when user copy boost/jsoncpp/libevent source files to rocketmq-client-cpp other then download them by build.sh
=> Update build.sh and readme

example/PullConsumeMessage.c, include/CProducer.h, include/CPullConsumer.h, include/CPullResult.h, include/CPushConsumer.h, src/extern/CProducer.cpp, src/extern/CPullConsumer.cpp, src/extern/CPushConsumer.cpp
Add name server domain support and refactor pull consumer.
1. add name server domain for the producer
2. add name server domain for the push consumer
3. add name server domain for the pull consumer
4. fix crash error when getting the message queue list from the broker
5. refactor pull messages from the broker
6. update pull consumer example
=> Add name server domain support and refactor pull consumer.

src/extern/CPullConsumer.cpp
fix issue-33 set maxOffset /minOffset/nextBeginOffset
=> [ISSUE #33] CPullConsumer cannot pull message because of pullResult without nextBeginOffset

CMakeLists.txt, include/DefaultMQPushConsumer.h, include/MQMessage.h, include/MQMessageExt.h, src/consumer/DefaultMQPushConsumer.cpp, src/extern/CProducer.cpp, src/message/MQDecoder.cpp, src/message/MQMessage.cpp, src/message/MQMessageExt.cpp, src/producer/DefaultMQProducer.cpp
- m_consumerService in DefaultMQPushConsumer is typo
- message level status is not not upper
- SetProducerInstanceName don't call
- repeat compress when retry send
=> Bugs fixed

src/common/UtilAll.cpp
`currentTimeMillis()` should return a unix time stamp instead of the spent milliseconds of this day.
This fix the issue [#38](https://github.com/apache/rocketmq-client-cpp/issues/38)
=> [ISSUE #38] Using std::chrono to get current time stamp

src/consumer/DefaultMQPushConsumer.cpp
If the push consumer has not been started, deallocate it will segfault in current code.
=> Fix push consumer dtor segfault

include/DefaultMQProducer.h, src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/common/AsyncCallbackWrap.cpp, src/common/AsyncCallbackWrap.h, src/producer/DefaultMQProducer.cpp, src/protocol/RemotingCommand.cpp, src/protocol/RemotingCommand.h, src/transport/ResponseFuture.cpp, src/transport/ResponseFuture.h, src/transport/TcpRemotingClient.cpp, src/transport/TcpRemotingClient.h
#44 autoRetryTimes doesn't work for producer async send #44
log of test and verify:
2019-Jan-03 14:08:30.493682:sendMessageAsync request:code:10,opaque:998,flag:0,seqNumber:999,body.size:22,header.size:442, timeout:3000, maxRetryTimes:3 retrySendTimes:1
2019-Jan-03 14:08:30.493725:invokeAsync success, addr:101.132.96.164:10911, code:10, opaque:998
2019-Jan-03 14:08:30.697239:code:2, remark:JAVA, version:273, opaque:998, flag:1, remark:[TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 201ms, size of queue: 223, headLen:217, bodyLen:0
2019-Jan-03 14:08:30.697285:processResponseCommand, code:10,opaque:998, maxRetryTimes:3, retrySendTimes:1
2019-Jan-03 14:08:30.697343:cancelTimerCallback: opaque:998
2019-Jan-03 14:08:30.697407:handleAsyncPullForResponseTimeout …
=> [Issue#44] Resolve RetrySendTimes doesn't Work for Async Send

CMakeLists.txt, include/DefaultMQProducer.h, src/common/sync_http_client.h, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/consumer/PullRequest.h, src/producer/DefaultMQProducer.cpp, src/thread/disruptor/sequence.h, src/transport/TcpTransport.cpp
issue #45 
1.fix unsafe code
2.format code style
3.fix build warnings
=> [ISSUE #45]Fix unsafe code ,build warnings and format code style

deploy.sh
I run deploy.sh and I get the error :
```bash
cp: cannot stat '/xxx/rocketmq-client-cpp/doc': No such file or directory
cp: cannot stat '/xxx/rocketmq-client-cpp/changelog': No such file or directory
```
=> remove copying the dir doc and changelog in deploy.sh because of the two dirs not exist

src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/MQClientFactory.cpp, src/MQClientFactory.h, src/common/AsyncArg.h, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/consumer/PullRequest.cpp, src/consumer/PullRequest.h, src/consumer/Rebalance.cpp, src/transport/TcpRemotingClient.cpp, src/transport/TcpRemotingClient.h
#43  One Consumer Consume One Message Twice At The Same Time
test and verify log:
[2019-Jan-08 23:52:32.136558](debug):pullMessageAsync set opaque:31, mq:MessageQueue [topic=jonnxu_topic, brokerName=broker-a, queueId=2]
[2019-Jan-08 23:52:32.136723](debug):invokeAsync success, addr:101.132.96.164:10911, code:11, opaque:31
[2019-Jan-08 23:52:49.905802](info):####### need delete the pullrequest for opaque:31, mq:MessageQueue [topic=jonnxu_topic, brokerName=broker-a, queueId=2]
[2019-Jan-08 23:52:49.905819](debug):succ deleted the async pullrequest for opaque:31, mq:MessageQueue [topic=jonnxu_topic, brokerName=broker-a, queueId=2]
[2019-Jan-08 23:52:49.905833](debug):cancelTimerCallback: opaque:31
[2019-Jan-08 23:52:49.905878](debug):handleAsyncPullForResponseTimeout opaque:31, e_code:0, …
=> [ISSUE#43] One Consumer Consume One Message Twice at the same time

src/transport/TcpTransport.cpp
The execution order of these two steps below are uncertain:
1. Assignment of 'm_ReadDatathread';
2. The thread runs 'TcpTransport::runThread';
If the thread runs first, the value of m_ReadDatathread will be NULL, the codes inside 'while (m_ReadDatathread) {}' will never be executed, then 'm_event_base_status' will never store 'true', so TcpTransport::connect will stay on the loop infintely.
=> [ISSUE #52]Fix infinite loop on tcptransport connect

src/consumer/PullRequest.cpp, src/consumer/PullRequest.h
Resolve the compile warning and bug
=> Resolve the compile warning and bug

src/protocol/RemotingCommand.cpp
fixed bug in RemotingCommand::Assign, that cause duplicated opaque allocated by s_seqNumber.
delete the operate of copy s_seqNumber in RemotingCommand::Assign.
XXXX
=> [ISSUE #84] fixed duplicated opaque

src/extern/CMessageExt.cpp
fixed the bug #86 
GetMessageStoreTimestamp not return StoreTimestamp
```
-    return ((MQMessageExt *) msg)->getBornTimestamp();
+    return ((MQMessageExt *) msg)->getStoreTimestamp();
```
XXXX
=> [ISSUE #86] fixed GetMessageStoreTimestamp not return StoreTimestamp

src/protocol/RemotingCommand.cpp, src/protocol/RemotingCommand.h
#77 replace lock with fetch_add(1) when allocate opaque
=> [ISSUE #77] optimize process of allocate opaque by atomic without lock.

src/common/dataBlock.cpp, src/common/dataBlock.h, src/consumer/PullResultExt.h
optimize memory copy in MemoryBlock by move constructor and move assignment.
=> Optimize: optimize memory copy in MemoryBlock by move constructor and move assignment.

src/transport/TcpTransport.cpp, src/transport/TcpTransport.h
Fixed this issue that cann't set namesrv with hostname
Modify TcpTransport::connect 
Calling inet_addr for a domain name returns INADDR_NONE
If return INADDR_NONE call gethostbyname get IP ADDRESS
roducer->setNamesrvAddr("mq.***.com:9876");
=> [ISSUE #42] Fixed this issue that cann't set namesrv with hostname

src/MQClientFactory.cpp, src/protocol/TopicRouteData.h
fixed the bug, can't select slave broker when findConsumerIds. this cause can't consume slave.
select broker random first, and use the master. if the master is unavailable, select a slave of it.
XXXX
=> [ISSUE #88] select slave broker when master broker is unavailable.

src/MQClientFactory.cpp, src/common/MQClient.cpp, src/common/NameSpaceUtil.cpp, src/common/NameSpaceUtil.h, src/log/Logging.cpp, src/log/Logging.h, src/protocol/CommandHeader.cpp, src/transport/TcpRemotingClient.cpp, src/transport/TcpTransport.cpp
[ISSUE #121 ]Support connect MQ endpoint
Change the signature context for send message
Support Aliyun MQ endpoint URL parser
Add function and line in the log file
Two kinds of Aliyun MQ topics:
1. topic for default instance(without InstanceID)
fulfill the name server address with endpoint and set ak, sk using the Session Credential API.
2. topic for your own InstanceID
change the GID to InstanceID+GID(InstanceID%GID),
change the topic to InstanceID+GID(InstanceID%GID),
fulfill the name server address with endpoint and set ak, sk using the Session Credential API.
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review …
=> [ISSUE #121]Support connect MQ endpoint with ACL

src/common/NameSpaceUtil.cpp
save string::find result into a string::size_type variable to compare with string::nops
replace unsigned int by auto to save string::size_type.
XXXX
=> [ISSUE #142] save string::find result into a string::size_type variable.

src/common/AsyncCallbackWrap.cpp, src/common/noncopyable.h, src/transport/EventLoop.cpp, src/transport/EventLoop.h, src/transport/ResponseFuture.cpp, src/transport/ResponseFuture.h, src/transport/TcpRemotingClient.cpp, src/transport/TcpRemotingClient.h, src/transport/TcpTransport.cpp, src/transport/TcpTransport.h
- feature: use only one event loop for all TcpTransport.
=> Update: update network interface.

src/protocol/CommandHeader.cpp
Resolve the issue for send batch message
Resolve the bug when send batch message without encode batch flag in SendMessageRequestHeader
SendResult: sendStatus:0,msgId:010011AC0000F15A000082BE6D0F0200,offsetMsgId:0BC1F01E00002A9F0000022B24C575D4,queueOffset:5467,transactionId:,messageQueue:MessageQueue [topic=MQ_INST_*************_BaoCMwkE%t-common-message, brokerName=qd5internet-01, queueId=1]
=> Resolve the bug without encode batch flag when send batch message

src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/MQClientFactory.cpp, src/MQClientFactory.h, src/common/AsyncArg.h, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/consumer/PullRequest.cpp, src/consumer/PullRequest.h, src/consumer/Rebalance.cpp, src/transport/TcpRemotingClient.cpp, src/transport/TcpRemotingClient.h
clean up.
remove removeDropedPullRequestOpaque and deleteOpaqueForDropPullRequest.
XXXX
=> remove removeDropedPullRequestOpaque and deleteOpaqueForDropPullRequest.

example/CBatchProducer.c, include/CBatchMessage.h, include/CProducer.h, src/extern/CBatchMessage.cpp, src/extern/CProducer.cpp
C batch sending interface
see example/CBatchProducer.c
=> Export send batch messages api in c style.

src/transport/TcpRemotingClient.cpp, src/transport/TcpRemotingClient.h
use io-thread pool and work-thread pool in network callback to resolve deadlock in block-request.
split TcpRemotingClient::m_ioService into m_dispatchService and m_handleService.
XXXX
=> [ISSUE #137] split TcpRemotingClient::m_ioService into m_dispatchService and m_handleService

example/TransactionProducer.cpp, include/MQMessage.h, include/SendResult.h, include/TransactionListener.h, include/TransactionMQProducer.h, include/TransactionSendResult.h, src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/MQClientFactory.cpp, src/MQClientFactory.h, src/message/MQMessageId.h, src/producer/SendResult.cpp, src/producer/TransactionMQProducer.cpp, src/protocol/CommandHeader.cpp, src/protocol/CommandHeader.h, src/protocol/RemotingCommand.cpp, src/transport/ClientRemotingProcessor.cpp, src/transport/ClientRemotingProcessor.h, src/transport/TcpRemotingClient.cpp
Support producer transaction message
realize the transaction message feature
executeLocalTransaction enter msg:Message [topic=trans_topic, flag=0, tag=*]
executeLocalTransaction transactionId:010011AC0000D95B0000AF8B32130100, return state: 2
sendMessageInTransaction  msgId: 010011AC0000D95B0000AF8B32130100
send RT more than: 2808 ms with msgid: 010011AC0000D95B0000AF8B32130100
checkLocalTransaction enter msg:MessageExt [queueId=0, storeSize=279, queueOffset=52809, sysFlag=0, bornTimestamp=1559554079663, bornHost=101.132.96.164, storeTimestamp=1559554081065, storeHost=101.132.96.164, msgId=010011AC0000D95B0000AF8B32130100, commitLogOffset=154611164, bodyCRC=1850051804, reconsumeTimes=0, preparedTransactionOffset=0,  Message [topic=trans_topic, flag=0, tag=*]]
checkLocalTransaction …
=> [Feature] Support producer transaction message

src/extern/CProducer.cpp, src/producer/DefaultMQProducer.cpp
optimize BatchMessage detection in DefaultMQProducer::sendKernelImpl, and fix bug in CProducer.
replace:
```
BatchMessage batchMessage;
bool isBatchMsg = (typeid(msg).name() == typeid(batchMessage).name());
```
with:
```
bool isBatchMsg = std::type_index(typeid(msg)) == std::type_index(typeid(BatchMessage));
```
XXXX
=> optimize BatchMessage detection in DefaultMQProducer::sendKernelImpl

include/CErrorMessage.h, src/common/MQClientErrorContainer.cpp, src/common/MQClientErrorContainer.h, src/extern/CErrorMessage.cpp, src/extern/CProducer.cpp, src/extern/CPullConsumer.cpp, src/extern/CPushConsumer.cpp
Add GetLatestErrorMessage feature
1、Add MQClientErrorContainer to save the latest error message
2、Provide C interface for getting the latest  error message
3、Modify C interface CPullConsumer,CPushConsumer,CPushConsumer  when occur error  use MQClientErrorContainer save error message
=> Add GetLatestErrorMessage feature

build.sh
to speed up compilation
Added the parameter `-j` for make in `build.sh`
=> Support muti-thread compile in build.sh

example/CBatchProducer.c, include/CErrorMessage.h, src/common/MQClientErrorContainer.cpp, src/common/MQClientErrorContainer.h, src/extern/CErrorMessage.cpp, src/extern/CProducer.cpp, src/extern/CPullConsumer.cpp, src/extern/CPushConsumer.cpp, src/transport/TcpRemotingClient.cpp, src/transport/TcpTransport.cpp
Format the code
MQClientErrorContainer.cpp
MQClientErrorContainer.h
.........
success
=> Format the codes and remove warnings

README.md, win32_build.bat
the command should be  this: .\b2 -j8 --with-serialization --with-atomic --with-log --with-locale --with-iostreams --with-system --with-regex --with-thread --with-date_time --with-chrono --with-filesystem --build-type=complete address-model=64 ,
not that: bjam.exe address-model=64 --with-serialization --with-atomic --with-log --with-locale --with-iostreams --with-system --with-regex --with-thread --with-date_time --with-chrono --with-filesystem  link=static  threading=multi variant=release runtime-link=shared
or the vs2015 will prompt the error can not find libboost_system-vc140-mt-gd-1_58.lib
XXXXX
XX
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not …
=> boost build64 on windows

src/consumer/Rebalance.cpp
#145  wrong lock flag for pull request in orderly consume when unlock
Rebalance.cpp 
success
=> [ISSUE#145] Wrong lock flag for pull request in orderly consume when unlock bug

distribution/deploy.sh
#177 
Modify deploy shell to package license and notice file
Move deploy.sh to distribution dir
Modify deploy shell to package license and notice file
sh deploy.sh
check the package
=> Modify deploy shell to package license and notice file

include/CProducer.h, src/extern/CProducer.cpp
Support user data in async callback
typedef void (*COnSendSuccessCallback)(CSendResult result, CMessage* msg, void* userData);
typedef void (*COnSendExceptionCallback)(CMQException e, CMessage* msg, void* userData);
ROCKETMQCLIENT_API int SendAsync(CProducer* producer,
CMessage* msg,
COnSendSuccessCallback cSendSuccessCallback,
COnSendExceptionCallback cSendExceptionCallback,
void* userData);
see the code
=> feat(producer): Support user data in async callback

src/producer/DefaultMQProducer.cpp
Currently, BatchMessage might be compressed like a normal Message (when it's size reached the point), and this compressing action will cause an sending error:
```
[2019-Sep-20 14:07:20.254324](error):processSendResponse error remark:java.lang.ArrayIndexOutOfBoundsException, java.util.zip.CRC32.update(CRC32.java:74), error code:1[processSendResponse:537]
[2019-Sep-20 14:07:20.254504](error):send error[sendMessageSync:381]
[2019-Sep-20 14:07:20.254706](error):msg: response is null,error:-1,in file </fakepath/rocketmq-client-cpp/src/MQClientAPIImpl.cpp> line:384[send:147]
```
1. Align to JAVA SDK: Skip compressing if message is a batch one. (You can refer to [apache/rocketmq](https://github.com/apache/rocketmq/blob/master/client/src/main/java/org/apache/rocketmq/client/impl/producer/DefaultMQ …
=> Fix: skip compressing if message is a batch one

src/common/MQClient.cpp, src/consumer/DefaultMQPushConsumer.cpp
reduce dependence on boost.
replace boost::thread::hardware_concurrency with std::thread::hardware_concurrency.
XXXX
=> replace boost::thread::hardware_concurrency with std version.

src/message/BatchMessage.cpp, src/producer/DefaultMQProducer.cpp, src/producer/StringIdMaker.cpp, src/producer/StringIdMaker.h, test/src/StringIdMakerTest.cpp
remove boost from StringIdMaker, and fixed some bugs.
1. remove boost from StringIdMaker;
2. fixed byte order bug;
3. fixed bug in setStartTime
XXXX
=> remove boost from StringIdMaker, and fixed some bugs.

include/DefaultMQPullConsumer.h, include/DefaultMQPushConsumer.h, include/MQConsumer.h, src/MQClientFactory.cpp, src/consumer/AllocateMQStrategy.h, src/consumer/ConsumeMessageConcurrentlyService.cpp, src/consumer/ConsumeMessageOrderlyService.cpp, src/consumer/ConsumeMsgService.h, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/consumer/FindBrokerResult.h, src/consumer/OffsetStore.cpp, src/consumer/OffsetStore.h, src/consumer/PullAPIWrapper.cpp, src/consumer/PullAPIWrapper.h, src/consumer/PullRequest.cpp, src/consumer/PullRequest.h, src/consumer/PullResult.cpp, src/consumer/PullResultExt.h, src/consumer/Rebalance.cpp, src/consumer/Rebalance.h, src/consumer/SubscriptionData.cpp, src/consumer/SubscriptionData.h
refactor(rebalance): use smart_ptr to manage pull request
=> refactor(rebalance): use smart_ptr to manage pull request

include/DefaultMQPullConsumer.h, include/DefaultMQPushConsumer.h, include/MQConsumer.h, src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/common/MQClient.cpp, src/consumer/ConsumeMessageConcurrentlyService.cpp, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/consumer/Rebalance.cpp
send back error when consuming failed.
use broker name to dend back.
=> fix(consumer): send back error when consuming failed.

src/extern/CProducer.cpp
[ISSUE #213 ]fix one bug in DestroyProducer which can cause the program core dump  
delete reinterpret_cast<DefaultMQProducer*>(pProducer);
to
delete reinterpret_cast<DefaultProducer*>(pProducer);
run producer in example
=> fix(producer) crash in DestroyProducer shutdown. 

.gitignore, build.sh, src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/MQClientFactory.cpp, src/MQClientFactory.h, src/MQClientManager.cpp, src/MQClientManager.h, src/common/TopAddressing.h, src/transport/TcpRemotingClient.h, test/src/MQClientAPIImpTest.cpp, test/src/MQClientFactoryTest.cpp
feat(client): add timer to clean off line broker and test case.
feat(client): add timer to clean off line broker and test case.
=> feat(client): add timer to clean off line broker and test case.

src/MQClientAPIImpl.cpp, src/MQClientFactory.cpp, src/common/AsyncCallbackWrap.cpp, src/common/AsyncCallbackWrap.h, src/common/MQVersion.cpp, src/common/MQVersion.h, src/common/VirtualEnvUtil.cpp, src/producer/DefaultMQProducer.cpp, src/protocol/CommandHeader.cpp, src/protocol/CommandHeader.h, src/protocol/RemotingCommand.cpp, test/src/MQClientAPIImpTest.cpp, test/src/common/MQVersionTest.cpp, test/src/common/VirtualEnvUtilTest.cpp, test/src/protocol/CommandHeaderTest.cpp
[fix #189] fix(send): try to use command v2 to send messages
=> fix(send): try to use command v2 to send messages

src/MQClientFactory.cpp, src/MQClientFactory.h, src/common/MQClient.cpp
fix #226 
feat(memleak): remove mem leak in factory schedule task.
=> feat(memleak): remove mem leak in factory schedule task.

build.sh
close #202 , close #204 , close #211 , close #224 , and same close #30 
Update Libevent version to 2.1.11-stable
=> feat(libevent): update libevent to v2.1.11 to avoid get mutex time out.

include/DefaultMQPushConsumer.h, src/MQClientAPIImpl.cpp, src/MQClientAPIImpl.h, src/consumer/ConsumeMessageConcurrentlyService.cpp, src/consumer/DefaultMQPushConsumer.cpp, src/protocol/CommandHeader.cpp, src/protocol/CommandHeader.h, test/src/MQClientAPIImpTest.cpp, test/src/protocol/CommandHeaderTest.cpp
close #229 
feat(version): add maxConsumerTimes to support higher client version
=> feat(version): add maxConsumerTimes to support higher client version

include/Arg_helper.h, include/AsyncCallback.h, include/DefaultMQProducer.h, include/DefaultMQPullConsumer.h, include/DefaultMQPushConsumer.h, include/MQClient.h, include/MQClientException.h, include/MQMessage.h, include/MQMessageExt.h, include/MQMessageListener.h, include/MQMessageQueue.h, include/MQSelector.h, include/MQueueListener.h, include/PullResult.h, include/SendResult.h, include/TransactionMQProducer.h, src/consumer/DefaultMQPullConsumer.cpp, src/consumer/DefaultMQPushConsumer.cpp, test/src/message/MQMessageIdTest.cpp, test/src/message/MQMessageTest.cpp
eat(apis):refactor apis for CPP styles
eat(apis):refactor apis for CPP styles
=> feat(apis):refactor apis for CPP styles

build.sh
The line `unzip -o ${fname_libevent} >unziplibevent.txt 2>&` creates the file `unziplibevent.txt` in the directory. So when setting the directory name with `libevent_dir=$(ls | grep libevent | grep .*[^zip]$)` the variable will have the name of two files and ` cd ${libevent_dir}` will prompt `cd: Too many arguments`.
Just adding the .txt extension to the exclusion list during the grep command is enough to solve the problem. In the end we have `libevent_dir=$(ls | grep libevent | grep .*[^zip^txt]$)`.
=> fix(build): fix variable in build script

src/protocol/CommandHeader.cpp
There is a heap-buffer-overflow risk that when the chars is not with '\0' or chars contain binary data, also may be a short parse. The string constructor should be replace with 'basic_string( const CharT* s, size_type count, const Allocator& alloc = Allocator() )' that specified chars length need be allocate other than expect the constructor 'basic_string( const CharT* s, const Allocator& alloc = Allocator() )' to find '\0' for calculating chars length.
Fix a heap-buffer-overflow risk for string constructor.
Has verified. Want a code review.
==108012==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60f000024f88 at pc 0xd7d1e8 bp 0x7ffdc5e171c0 sp 0x7ffdc5e17198
READ of size 169 at 0x60f000024f88 thread T0 (app_dispatchsrv)
#0 0xd7d1e7 in __interceptor_strlen …
=> heap-buffer-overflow risk

dep/build.sh, rpm/build.sh, src/producer/DefaultMQProducer.cpp, src/producer/TransactionMQProducer.cpp
close #243 
chore(license): add missed license header in some files
chore(license): add missed license header in some files
=> chore(license): add missed license header in some files

build.sh
fix(build): fix variable check error in the build script
fix(build): fix variable check error in the build script
=> fix(build): fix variable check error in the build script

src/MQClientFactory.cpp, src/extern/CProducer.cpp
close #247 
fix(transaction): failed to select transaction producer to call local state checker
=> fix(transaction): failed to select transaction producer to call local state checker

src/extern/CProducer.cpp
refactor(transaction): use userdata to cache the local checker callback
refactor(transaction): use userdata to cache the local checker callback
=> refactor(transaction): use userdata to cache the local checker callback

CMakeLists.txt, build.sh, distribution/deploy.sh, format.sh
（1）Declare variables explicitly, and clarify variable types.
（2）Format the code style.
（3）Add asan support for memory address out of range checking.
（4）Add lsan support for memory leak checking.
（5）Simplify redirection semantics for easy understanding
Add asan/lsan support, and formatting code. 
Has verified. Want a code review.
=> feat(memory): add asan/lsan support, and formatting code.

test/src/common/MemoryBlockTest.cpp
（1）Fix bad and invalid test cases.
（2）Add a test case for boundary 0.
（3）Fix the heap-buffer-overflow bug.
Fix the heap-buffer-overflow bug and bad/invalid test cases.
Has been verified and passed the ASAN check.
==32183==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ed70 at pc 0x7f1378d60a1e bp 0x7fff6c9be8c0 sp 0x7fff6c9be8b8
READ of size 20 at 0x60200000ed70 thread T0
#0 0x7f1378d60a1d in rocketmq::MemoryBlock::MemoryBlock(void const*, unsigned long) (/home/yizhe.wcm/PR/rocketmq-client-cpp/bin/librocketmq.so+0x503a1d)
#1 0x4dba7a in memoryBlock_init_Test::TestBody() (/home/yizhe.wcm/PR/rocketmq-client-cpp/test/bin/MemoryBlockTest+0x4dba7a)
#2 0x50e87b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void …
=> fix(test): fix the heap-buffer-overflow bug and bad/invalid test cases.

test/src/common/big_endianTest.cpp
Fix heap-buffer-overflow due to wrong use of strcpy.
Fix heap-buffer-overflow due to wrong use of strcpy.
Verified. Want a code review.
==45669==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ed10 at pc 0x4dc0a5 bp 0x7ffee848e850 sp 0x7ffee848e848
WRITE of size 9 at 0x60200000ed10 thread T0
#0 0x4dc0a4 in big_endian_bigEndianObject_Test::TestBody() (/home/yizhe.wcm/PR/rocketmq-client-cpp/test/bin/big_endianTest+0x4dc0a4)
#1 0x50c7fd in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/yizhe.wcm/PR/rocketmq-client-cpp/test/bin/big_endianTest+0x50c7fd)
#2 0x50652b in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void …
=> fix(memory): heap-buffer-overflow due to wrong use of strcpy.

build.sh
Modify the default number of threads used for compilation on Linux and MAC platforms to be the number of CPU logical cores, rather than hardcode.
Modify the default number of threads used for compilation on Linux and MAC platforms to be the number of CPU logical cores, rather than hardcode.
Verified. Want a code review.
=> refactor(build): use dynamic cpu cores to compile code.

src/MQClientFactory.cpp, test/src/MQClientManagerTest.cpp
… it is not used after initialization.
Fix the heap-use-after-free risk caused by direct deconstruction when it is not used after initialization.
Fix the heap-use-after-free risk caused by direct deconstruction when it is not used after initialization.
Want a code review.
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from MQClientManagerTest
[ RUN      ] MQClientManagerTest.getClientFactory
=================================================================
==124436==ERROR: AddressSanitizer: heap-use-after-free on address 0x6110000096f8 at pc 
0x7efe51699cba bp 0x7efe4bdfac20 sp 0x7efe4bdfac18
WRITE of size 8 at 0x6110000096f8 thread T4 (RemotingAsioT)
[       OK ] MQClientManagerTest.getClientFactory (14 ms)
[ RUN      ] …
=> Fix the heap-use-after-free risk caused by direct deconstruction when it is not used after initialization.

src/consumer/DefaultMQPushConsumerImpl.cpp
Close #282  send message back failed some time because timeout set to short.
modify the time out set of the sendmessageback function.
=> [ISSUE #282] modify the time out set of the sendmessageback function.

src/consumer/DefaultMQPushConsumerImpl.cpp
=> [ISSUE #291] Use separate factory for trace producer of push consumer.

build.sh
Use the archive download URL for OpenSSL to avoid fail to download
=> [ISSUE #296] Use the archive download URL for OpenSSL to avoid fail to download

src/transport/TcpTransport.cpp
Avoid crash when resolve domain failed.
Catch exception when resolve domain failed.
XXXX
=> [ISSUE #303] Catch exception when resolve domain failed

rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
fix bug in rpm spec
make librocketmq.so accessible to dlopen()
XXXX
=> Add rocketmq libpath to ldconf to support dlopen in CentOS

src/consumer/DefaultMQPushConsumerImpl.cpp, src/consumer/PullRequest.cpp
Resolves #322 
Fix how PullConsumer checks cached messages count in a PullRequest.
Check messages in both m_msgTreeMap and m_msgTreeMapTemp.
The original issue is not reproducible with this patch.
=> [ISSUE #322] Fix how PullConsumer checks cached messages count in a PullRequest

include/MQMessageExt.h, src/transport/SocketUtil.h
(cherry picked from commit 6108dc5619a58c8b54e4604cb6dfedf5d2de74a1)
fix possible socket compile error on windows
avoid _WINSOCKAPI_ redefine error when include Windows.h and Winsock2.h at same time
verified using "Visual Studio 17 2022"
=> avoid _WINSOCKAPI_ redefine error when include Windows.h and Winsock2.h at same time

src/producer/StringIdMaker.cpp, src/transport/TcpTransport.cpp
avoid possible type conversion compile error
avoid possible type conversion compile error
verified using "Visual Studio 17 2022"
=> avoid possible type conversion compile error

src/transport/ClientRemotingProcessor.cpp, src/transport/ClientRemotingProcessor.h
(cherry picked from commit 57b584103a30ba1386560b8e54d209975ec7b055)
optimize function call
param “mq” is read only,pass by reference instead of value
compile successful
=> param “mq” is read only,pass by reference instead of value

build.sh
close #436 
- Downloading openssl package without checking certificate in compile shell.
- Downloading boost package without checking certificate in compile shell.
=> [ISSUE 436] Downloading dependent packages without checking certificate in compile shell.

build.sh, src/common/ByteOrder.h, src/common/UtilAll.h, src/extern/CProducer.cpp, src/extern/CPullConsumer.cpp, src/extern/CPushConsumer.cpp, src/log/Logging.cpp, src/log/Logging.h
#400
Add the log path to the environment variable by using setenv function, and set this path before the log object is initialized.
By setting producer log path to "/logs/producer/cpp/", the log file was saved in "~/logs/producer/cpp/", and the main log file name is "rocketmq_client.log", backup log file name's format is "rocketmq_client_%Y%m%d-%N.log". As follows:
We use boost1.78.0 to make backup log file name configurable.
=> make log dir configurable and make log name compatible with RocketMQ main project

include/SendResult.h, src/MQClientAPIImpl.cpp, src/producer/SendResult.cpp, src/protocol/RemotingCommand.cpp, src/protocol/RemotingCommand.h
Relate to #435
Support receiving traceOn signal, which indicates whether to disable message trace.
- add interface `SendResult::getTraceOn()`
- complete `extFields` according to [this](https://github.com/apache/rocketmq/blob/develop/docs/cn/design.md#22-%E5%8D%8F%E8%AE%AE%E8%AE%BE%E8%AE%A1%E4%B8%8E%E7%BC%96%E8%A7%A3%E7%A0%81)
=> [ISSUE-435][PART-A]Support receiving traceOn signal.

rpm/build.sh
fix build bug
```log
error: failed to create directory %{_specdir}: /root/rpmbuild/SPECS: 没有那个文件或目录
cp: 无法获取'/root/rpmbuild/RPMS/x86_64/*.rpm' 的文件状态(stat): 没有那个文件或目录
```
XXXXX
XX
XXXX
=> fix rpm build bug

src/MQClientAPIImpl.cpp, src/producer/DefaultMQProducerImpl.cpp
=> [ISSUE #485]fix: send failed show exception details

src/transport/TcpRemotingClient.cpp
When connecting to a NameServer with multiple instances, implement load balancing to distribute connections across available instances.
related Issue: https://github.com/apache/rocketmq-client-cpp/issues/492
In TcpRemotingClient.cpp, the CreateNameServerTransport method currently hardcodes index 0 to select a NameServer address from m_namesrvAddrList. However, the m_namesrvAddrList is not randomized during address updates, leading to all clients defaulting to the first address in the list. This results in uneven load distribution.
=> [ISSUE #492] Add Load Balancing for NameServer Connections
