CMakeLists.txt
example/CMakeLists.txt
example/Producer.c
example/PushConsumeMessage.c
include/CCommon.h
include/CMessage.h
include/CMessageExt.h
include/CProducer.h
include/CPullConsumer.h
include/CPushConsumer.h
include/CSendResult.h
src/consumer/DefaultMQPullConsumer.cpp
src/consumer/DefaultMQPushConsumer.cpp
src/producer/DefaultMQProducer.cpp

1. C Samples include send message sync and push consumer;
2. Support C compile;
3, initialize sagaction.

Add C Samples and Initialize Sigaction

---

.gitignore
example/PullConsumeMessage.c
include/CMessageQueue.h
include/CPullConsumer.h
include/CPullResult.h
src/extern/CPullConsumer.cpp

Release C API to support Pull Consumer

Support Pull Consumer

---

include/CProducer.h
src/extern/CProducer.cpp

Support order producer.
SendMessageOrderly interface is added to support producer sending messages sequentially。

Support order producer

---

include/CPushConsumer.h
src/extern/CPushConsumer.cpp

Support order consumerr.
Add C-Style  API RegisterMessageCallbackOrderly and UnregisterMessageCallbackOrderly.

Add C-Style  API RegisterMessageCallbackOrderly and UnregisterMessageCallbackOrderly

---

.gitignore
CMakeLists.txt
src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/ConsumeMessageOrderlyService.cpp
src/thread/task_queue.cpp
src/transport/TcpRemotingClient.cpp

- Don't include system/prctl.h on macOS
- Don't depend on librt on macOS

Fix compile errors on macOS

---

include/CCommon.h
include/CPushConsumer.h
src/extern/CPushConsumer.cpp

Support  set  consume model.
Add C-Style  API setMessageModel

Add C-Style API setMessageModel

---

README.md
deploy.sh
src/extern/CPushConsumer.cpp

Update deploy script

---

README.md
build.sh

Add description for Mac platform and delete key world function for build.sh

Add description for Mac platform and delete key world function for build.sh

---

build.sh

build.sh: line 247: cd: boost.txt: Not a directory

Hotfix:auto build error

---

example/PushConsumerOrderly.c

Add a example of orderly PushConsumer
Add  the file of 

Add a example of orderly PushConsumer

---

src/consumer/Rebalance.cpp

resolve issue #89 
it will crash when init orderly consume  
when there is only SLAVE node, it need judge the point is null or not before use it
NA

[ISSUE#89] it will crash when init orderly consume

---

src/protocol/KVTable.h
test/src/protocol/KVTableTest.cpp
test/src/protocol/LockBatchBodyTest.cpp
test/src/protocol/MessageQueueTest.cpp

unit-test-protocol-2

---

src/common/NamesrvConfig.h
test/src/common/MemoryOutputStreamTest.cpp
test/src/common/NamesrvConfigTest.cpp
test/src/common/PermNametTest.cpp
test/src/common/PullSysFlagTest.cpp

unit-test-common-2

---

test/src/extern/CProducerTest.cpp

environmental anomaly

---

include/CProducer.h
src/extern/CProducer.cpp

#118 Support send message oneway orderly for C API
Add SendMessageOnewayOrderly C API
send success

[ISSUE#118] Support send message oneway orderly for C API

---

test/src/common/MemoryBlockTest.cpp
test/src/extern/CMessageTest.cpp
test/src/extern/CProducerTest.cpp
test/src/extern/CPushConsumerTest.cpp
test/src/protocol/RemotingCommandTest.cpp
test/src/transport/ClientRemotingProcessorTest.cpp

crash, test cash error and compile warning for unit test cash
set the chang files: test/src/*
##################  test  start  ###########
BatchMessageTest success
big_endianTest success
ClientRemotingProcessorTest success
ClientRPCHookTest success
CMessageExtTest success
CMessageTest success
CommandHeaderTest success
ConsumerRunningInfoTest success
CProducerTest success
CPullConsumerTest success
CPushConsumerTest success
HeartbeatDataTest success
KVTableTest success
LockBatchBodyTest success
MemoryBlockTest success
MemoryOutputStreamTest success
MessageQueueTest success
MQDecoderTest success
MQMessageExtTest success
MQMessageIdTest success
MQMessageQueueTest success
MQMessageTest success
NamesrvConfigTest success
PermNametTest success
ProcessQueueInfoTest success
PullSysFlagTest success …

Resolve crash, test cash error and compile warning for unit test cash

---

src/transport/TcpRemotingClient.cpp

[ISSUE #134 ]Fixed ResponseFuture leak when invokeHeartBeat is failed.
delete ResponseFuture when invokeHeartBeat is failed.
XXXX

[ISSUE #134] Fixed ResponseFuture leak when invokeHeartBeat is failed.

---

CMakeLists.txt
project/CMakeLists.txt

Modify project name to rocketmq-client-cpp in CMakeList file
Modify project name to rocketmq-client-cpp in CMakeList file

Modify project name to rocketmq-client-cpp in CMakeList file

---

src/common/NameSpaceUtil.cpp
src/common/NameSpaceUtil.h

Change the string length from int to unsigned int
Change the string length from int to unsigned int
build

Fix build warnings in namespace util

---

test/src/transport/ResponseFutureTest.cpp

ci erren
see ResponseFutureTest
see ResponseFutureTest

change ResponseFutureTest

---

src/transport/TcpRemotingClient.cpp
src/transport/TcpRemotingClient.h

manage sync future and async future in single future table.
merge m_futureTable and m_asyncFutureTable together.
XXXX

merge m_futureTable and m_asyncFutureTable together.

---

distribution/LICENSE-BIN
distribution/NOTICE-BIN
src/thread/disruptor/batch_descriptor.h
src/thread/disruptor/claim_strategy.h
src/thread/disruptor/event_processor.h
src/thread/disruptor/event_publisher.h
src/thread/disruptor/exception_handler.h
src/thread/disruptor/exceptions.h
src/thread/disruptor/interface.h
src/thread/disruptor/ring_buffer.h
src/thread/disruptor/sequence.h
src/thread/disruptor/sequence_barrier.h
src/thread/disruptor/sequencer.h
src/thread/disruptor/utils.h
src/thread/disruptor/wait_strategy.h

Add license for 3-rd party code
add binary licenses.
see in distribution directions

Add license and notice binary to prepare release

---

src/common/MQClientErrorContainer.cpp
src/common/MQClientErrorContainer.h
src/extern/CErrorMessage.cpp
src/extern/CProducer.cpp
src/extern/CPullConsumer.cpp
src/extern/CPushConsumer.cpp

fixed dangling point in GetLatestErrorMessage.
use thread_local variable store err.
XXXX

fixed dangling point in GetLatestErrorMessage.

---

include/CProducer.h
src/extern/CProducer.cpp

#187 add method for orderly message sending by shardingkey
int SendMessageOrderlyByShardingKey(CProducer* producer,
CMessage* msg, const char * shardingKey, CSendResult* result);
add method for orderly message sending by shardingkey

feat(producer): add method for orderly message sending by shardingkey

---

example/AsyncProducer.cpp
example/Producer.c

style(example):format the code style in example

style(example):format the code style in example

---

src/consumer/DefaultMQPushConsumer.cpp

fixed typo bug in DefaultMQPushConsumer::getConsumerRunningInfo.
change 'flase' to 'false'.
XXXX

fixed typo bug in DefaultMQPushConsumer::getConsumerRunningInfo.

---

src/transport/TcpRemotingClient.cpp
src/transport/TcpTransport.cpp

do some optimization in transport layer
1. optimize lock-wait by double-check when waitTcpConnectEvent.
2. always addTimerCallback in invokeAsync for avoid memory leak when pass NULL cbw and not response.
XXXX

Optimize transport layer

---

include/DefaultMQProducer.h
include/DefaultMQPullConsumer.h
include/DefaultMQPushConsumer.h
include/MQClient.h
include/MQConsumer.h
src/common/MQClient.cpp
src/common/MessageAccessor.cpp
src/common/MessageAccessor.h
src/common/NameSpaceUtil.cpp
src/common/NameSpaceUtil.h
src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/ConsumeMessageOrderlyService.cpp
src/consumer/DefaultMQPullConsumer.cpp
src/consumer/DefaultMQPushConsumer.cpp
src/producer/DefaultMQProducer.cpp

feat(namespace): add name space support

feat(namespace): add name space support

---

include/DefaultMQPullConsumer.h
include/DefaultMQPushConsumer.h
include/MQConsumer.h
src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/ConsumeMessageOrderlyService.cpp
src/consumer/ConsumeMsgService.h
src/consumer/DefaultMQPullConsumer.cpp
src/consumer/DefaultMQPushConsumer.cpp

#208 
add return status fo rsendback, and retry to consume again locally.

fix(consumer): fix the issue that msg lost when send back to broker failed.

---

src/MQClientAPIImpl.cpp
src/common/AsyncCallbackWrap.cpp
src/common/AsyncCallbackWrap.h
src/transport/ResponseFuture.cpp
src/transport/ResponseFuture.h
src/transport/TcpRemotingClient.cpp
src/transport/TcpRemotingClient.h
test/src/MQClientAPIImpTest.cpp
test/src/transport/ResponseFutureTest.cpp

feat(callback): use start pointer to manager callbacks

feat(callback): use start pointer to manager callbacks

---

src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/DefaultMQPushConsumer.cpp

feat(consumer): remove event if consumer service shutdown

feat(consumer): remove event if consumer service shutdown

---

dep/build.sh
rpm/build.sh

fix(package):update package script
fix(package):update package script

fix(package):update package script

---

README.md
dep/rocketmq_amd64/DEBIAN/control
distribution/deploy.sh
rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
src/common/DefaultMQClient.cpp

feat(release): update version to prepare to release v2
feat(release): update version to prepare to release v2

feat(release): update version to prepare to release v2

---

dep/rocketmq_amd64/DEBIAN/control
dep/rocketmq_amd64/DEBIAN/postinst
rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec

style(license): add license header for script files
style(license): add license header for script files

style(license): add license header for script files

---

dep/rocketmq_amd64/DEBIAN/control
dep/rocketmq_amd64/DEBIAN/postinst

fix(package): remove unnecessary lines and use sh to run postinst.
the control file should not contain unnecessary lines.

fix(package): remove unnecessary lines and use sh to run postinst

---

include/DefaultMQProducer.h
include/DefaultMQPushConsumer.h
include/TransactionMQProducer.h
src/common/DefaultMQClient.cpp
src/consumer/DefaultMQPushConsumer.cpp
src/include/DefaultMQClient.h
src/producer/DefaultMQProducer.cpp
src/producer/TransactionMQProducer.cpp

refactor(warning): remove warnings in header files

refactor(warning): remove warnings in header files

---

build.sh

close #253 
feat(build): add the script to package static lib on macOS.

feat(build): add the script to package static lib on macOS.

---

build.sh
include/SendResult.h
src/MQClientAPIImpl.cpp
src/producer/SendResult.cpp
src/protocol/CommandHeader.cpp
src/protocol/CommandHeader.h
test/src/producer/DefaultMQProducerImplTest.cpp
test/src/protocol/CommandHeaderTest.cpp

feat(producer): add regionId support in the send result

feat(producer): add regionId support in the send result 

---

dep/rocketmq_amd64/DEBIAN/control
distribution/deploy.sh
rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
src/common/DefaultMQClient.cpp

chore(release): update version to release 2.0.1

chore(release): update version to release 2.0.1

---

dep/rocketmq_amd64/DEBIAN/control
distribution/deploy.sh
rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
src/common/DefaultMQClient.cpp

close #278 
[ISSUE #278] update versions to release 2.1.0

[ISSUE #278] update versions to release 2.1.0

---

include/CCommon.h
include/CProducer.h
include/CPushConsumer.h
include/TransactionMQProducer.h
src/extern/CProducer.cpp
src/extern/CPushConsumer.cpp
src/producer/TransactionMQProducer.cpp
test/src/extern/CProducerTest.cpp
test/src/extern/CPushConsumerTest.cpp

[close #280] add message trace shift for C style apis.
add message trace shift for C style apis.

[ISSUE #280] add message trace shift for C style apis.

---

src/MQClientAPIImpl.cpp
src/MQClientFactory.cpp
src/common/AsyncCallbackWrap.cpp
src/consumer/DefaultMQPullConsumerImpl.cpp
src/consumer/DefaultMQPushConsumerImpl.cpp
src/consumer/OffsetStore.cpp
src/consumer/Rebalance.cpp
src/producer/DefaultMQProducerImpl.cpp

close #284 
fix(log): sometime the log cause coredump
fix(log): sometime the log cause coredump

[ISSUS #284] sometime the log in rebalance will cause core dump.

---

src/consumer/DefaultMQPushConsumerImpl.cpp

[ISSUE #286] Add null pointer check before push consumer shutdown.

---

dep/rocketmq_amd64/DEBIAN/control
distribution/deploy.sh
rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
src/common/DefaultMQClient.cpp

close #289
Update version to 2.2.0 to release.

[ISSUE #289] Update version to 2.2.0 to release.

---

src/consumer/DefaultMQPushConsumerImpl.cpp
src/consumer/PullRequest.cpp
src/consumer/Rebalance.cpp

[ISSUE #293] reset pull call back by new pull request event time

[ISSUE #293] reset pull call back by new pull request event time

---

CMakeLists.txt
src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/ConsumeMessageOrderlyService.cpp
src/consumer/DefaultMQPushConsumerImpl.cpp
src/protocol/ConsumerRunningInfo.cpp
src/protocol/ConsumerRunningInfo.h
src/status/ConsumeStats.cpp
src/status/ConsumeStats.h
src/status/StatsItem.h
src/status/StatsServer.cpp
src/status/StatsServer.h
src/status/StatsServerManager.cpp
src/status/StatsServerManager.h
test/src/protocol/ConsumerRunningInfoTest.cpp

close #272 
Try to support messaging consuming tps status
Add a new status service to calc tps.

[ISSUE #272]Try to support messaging consuming tps status

---

src/consumer/ConsumeMessageConcurrentlyService.cpp
src/consumer/DefaultMQPushConsumerImpl.cpp
src/status/StatsServer.cpp
src/status/StatsServer.h

close #304 
add pull RT and TPS status.

[ISSUE #304]add pull RT and TPS status.

---

src/common/ClientRPCHook.cpp

close #306 
[ISSUE #306] Add binary message body to signatures.

[ISSUE #306] Add binary message body to signatures.

---

src/MQClientAPIImpl.cpp
src/MQClientInstance.cpp

Fixed uniqMsgId in batch send result.
Fixed string build process for uniqMsgId in MQClientAPIImpl::processSendResponse.
XXXX

Fixed uniqMsgId in batch send result

---

src/MQClientAPIImpl.cpp

[ISSUE #308]add default topic check to filter warning logs.

---

src/common/UtilAll.h
test/src/protocol/CommandHeaderTest.cpp

Fix Bug for Send batch messages
let bool fields in request header be serialized into bool rather than string "1" or "0"; 
XXXX

fix SendMessageRequestHeader Serialization bug

---

.gitignore
build.sh
include/CMessage.h
include/CMessageExt.h
src/extern/CMessage.cpp
src/extern/CMessageExt.cpp
test/src/extern/CMessageExtTest.cpp
test/src/extern/CMessageTest.cpp

Add function to reliably acquire message body length
Fix a few typo and grammar error
CMessage.{h,cpp}, CMessageExt.{h,cpp}
XXXX
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before requesting the community to review your PR`.

Add function to reliably acquire message body length

---

.vscode/settings.json
api/rocketmq/Message.h
bazel/rocketmq_deps.bzl
proto/apache/rocketmq/v2/definition.proto
proto/apache/rocketmq/v2/service.proto
src/main/cpp/client/ClientManagerImpl.cpp
src/main/cpp/client/TelemetryBidiReactor.cpp
src/main/cpp/client/include/ClientConfig.h
src/main/cpp/rocketmq/ConsumeMessageServiceImpl.cpp
src/main/cpp/rocketmq/ConsumeTask.cpp
src/main/cpp/rocketmq/ProducerImpl.cpp
src/main/cpp/rocketmq/SendContext.cpp
src/main/cpp/rocketmq/include/ConsumeMessageService.h
src/main/cpp/rocketmq/include/ConsumeMessageServiceImpl.h
src/main/cpp/rocketmq/include/ProducerImpl.h
src/main/cpp/rocketmq/include/PushConsumerImpl.h
src/main/cpp/rocketmq/include/SendContext.h
src/main/cpp/stats/BUILD.bazel
src/main/cpp/stats/ConsumeStats.cpp
src/main/cpp/stats/MetricBidiReactor.cpp
src/main/cpp/stats/OpencensusExporter.cpp
src/main/cpp/stats/PublishStats.cpp
src/main/cpp/stats/Tag.cpp
src/main/cpp/stats/include/ConsumeStats.h
src/main/cpp/stats/include/Exporter.h
src/main/cpp/stats/include/MetricBidiReactor.h
src/main/cpp/stats/include/OpencensusExporter.h
src/main/cpp/stats/include/PublishStats.h
src/main/cpp/stats/include/Tag.h
src/main/cpp/stats/tests/PublishStatsTest.cpp

XXXXX
Instrument with opencensus to collect various metrics
XXXX

Instrument with opencensus to collect various metrics

---

src/transport/TcpTransport.cpp

Fix compile error of type conversion, to close #423 
XX
XXXX

fix: compile error of type conversion

---

src/transport/ClientRemotingProcessor.cpp

fix memory leak
do not use point variable "offsetBody"  again, delete it
compile success

fix memory leak

---

src/producer/DefaultMQProducerImpl.cpp
src/producer/DefaultMQProducerImpl.h
src/protocol/ConsumerRunningInfo.cpp
src/protocol/ConsumerRunningInfo.h

(cherry picked from commit 1ba67b60a35bbc51f8ccbd7fb559d2513712b732)
pass by reference
pass by reference
compile success

pass by reference

---

src/MQClientManager.cpp
src/protocol/TopicRouteData.h

(cherry picked from commit aa6f8bbb5512ae5ea542a0ebf7e808778e26f377)
change seed, otherwise random number will not be changed
XX
XXXX

change seed, otherwise random number will not be changed

---

src/MQClientAPIImpl.cpp
src/MQClientAPIImpl.h
src/producer/DefaultMQProducerImpl.cpp
src/protocol/CommandHeader.h

reduce unnecessary memory malloc
XX
XXXX

reduce unnecessary memory malloc

---

src/common/ByteOrder.h
src/log/Logging.h
src/producer/TransactionMQProducerImpl.h

(cherry picked from commit 00a4d1cae74a4c01d998f651dc37c9c82e6fe1c2)
adapt to new version of boost when using smart ptr
adapt to new version of boost and fix compile error
verified using boost 1.79

adapt to new version of boost and fix compile error

---

src/common/NameSpaceUtil.cpp
src/consumer/ConsumeMessageHookImpl.cpp
src/producer/DefaultMQProducerImpl.cpp
src/producer/SendMessageHookImpl.cpp
src/trace/ConsumeMessageContext.h
src/trace/SendMessageContext.h
src/trace/TraceBean.h
src/trace/TraceConstant.cpp
src/trace/TraceConstant.h
src/trace/TraceContext.h
src/trace/TraceUtil.cpp
src/trace/TraceUtil.h
test/src/trace/TraceUtilTest.cpp

Fix typo: contant -> constant
- replace `Contant` with `Constant`
- rename file `src/trace/TraceContant.cpp` as `src/trace/TraceConstant.cpp`
- rename file `src/trace/TraceContant.h` as `src/trace/TraceConstant.h`
XXXX

[ISSUE-435][PART-B] Fix typo in trace constant "contant -> constant".

---

src/consumer/ConsumeMessageHookImpl.cpp
src/producer/DefaultMQProducerImpl.cpp
src/producer/SendMessageHookImpl.cpp

Turn off message trace automatically for the `producer`, when the `sandResult` suggests to do so.
turn off message trace before `sendKernelImpl` returning `sendResult`.
XXXX

[ISSUE-435][PART-C] Automatically turn off message trace.

---

src/transport/TcpRemotingClient.cpp

[ISSUE #450] fix connect fail when connect concurrently

---

src/consumer/DefaultMQPushConsumerImpl.cpp

fix negtive diff in some case
XX
delete and create topic

Fix negtive diff in-some-case

---

src/consumer/DefaultMQPushConsumerImpl.cpp

[ISSUE #477] fix: metrics pull rt was reported as consume rt

---

test/src/MQClientAPIImpTest.cpp
test/src/extern/CPullConsumerTest.cpp
test/src/producer/DefaultMQProducerImplTest.cpp

related: https://github.com/apache/rocketmq-client-cpp/issues/496
Fix compilation issues in test code
Modify the call parameters of **okMQAResult** and **sendMessage** in the test
After modification, normal unit testing can be performed
100% tests passed

[ISSUE #496] Fix compilation issues in test code
